
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EtudiantService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EtudiantService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Create")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Create", targetNamespace = "http://service/", className = "service.Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://service/", className = "service.CreateResponse")
    @Action(input = "http://service/EtudiantService/CreateRequest", output = "http://service/EtudiantService/CreateResponse")
    public String create(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<service.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiants", targetNamespace = "http://service/", className = "service.GetEtudiants")
    @ResponseWrapper(localName = "getEtudiantsResponse", targetNamespace = "http://service/", className = "service.GetEtudiantsResponse")
    @Action(input = "http://service/EtudiantService/getEtudiantsRequest", output = "http://service/EtudiantService/getEtudiantsResponse")
    public List<Etudiant> getEtudiants();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://service/", className = "service.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://service/", className = "service.DeleteResponse")
    @Action(input = "http://service/EtudiantService/DeleteRequest", output = "http://service/EtudiantService/DeleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Update")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Update", targetNamespace = "http://service/", className = "service.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://service/", className = "service.UpdateResponse")
    @Action(input = "http://service/EtudiantService/UpdateRequest", output = "http://service/EtudiantService/UpdateResponse")
    public String update(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
